# Generated by Django 4.1.1 on 2022-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from12', models.CharField(max_length=15)),
                ('to', models.CharField(max_length=15)),
                ('journey_date', models.DateField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='station_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
