# Generated by Django 4.1.1 on 2022-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='chair',
            field=models.CharField(default='class', max_length=15),
        ),
    ]
