# Generated by Django 4.1.1 on 2022-12-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0003_passenger_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='passenger_name',
            field=models.CharField(default='name', max_length=15),
        ),
        migrations.DeleteModel(
            name='passenger_details',
        ),
    ]
