# Generated by Django 4.1.1 on 2022-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0005_alter_journey_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='passenger_name',
            field=models.CharField(default='name', max_length=15),
        ),
    ]
