# Generated by Django 4.1.1 on 2022-12-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0006_alter_journey_passenger_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='journey',
            new_name='journeys',
        ),
    ]
