# Generated by Django 4.1.1 on 2022-12-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0007_rename_journey_journeys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='journeys',
            new_name='journey',
        ),
    ]
