# Generated by Django 4.1.1 on 2022-12-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0010_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='passenger_name',
        ),
    ]
