# Generated by Django 4.1.1 on 2022-12-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0011_remove_journey_passenger_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='journey',
        ),
    ]
