# Generated by Django 4.1.1 on 2022-12-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0014_delete_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_nm', models.CharField(default='null', max_length=15)),
                ('from12', models.CharField(max_length=15)),
                ('to', models.CharField(max_length=15)),
                ('journey_date', models.DateField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('chair', models.CharField(default='class', max_length=15)),
            ],
        ),
    ]
