# Generated by Django 4.1.1 on 2022-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0020_train_name_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_name',
            name='from_dist',
            field=models.CharField(default='from', max_length=15),
        ),
    ]
