# Generated by Django 4.1.1 on 2022-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0021_train_name_from_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_name',
            name='chair',
            field=models.CharField(default='chair', max_length=10),
        ),
    ]
