# Generated by Django 4.1.1 on 2022-12-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0022_train_name_chair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_name',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_tick.journey'),
        ),
    ]
