# Generated by Django 4.1.1 on 2022-12-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0023_alter_train_name_chair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_name',
            old_name='chair',
            new_name='chair_class',
        ),
    ]
