# Generated by Django 4.1.1 on 2022-12-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0024_rename_chair_train_name_chair_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_name',
            name='chair_class',
        ),
        migrations.AddField(
            model_name='station_name',
            name='chair_class',
            field=models.CharField(default='class', max_length=15),
        ),
    ]
