# Generated by Django 4.1.1 on 2022-12-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0025_remove_train_name_chair_class_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='train_name',
            new_name='train_info',
        ),
    ]
