# Generated by Django 4.1.1 on 2022-12-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0026_rename_train_name_train_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='train_info',
        ),
    ]
