# Generated by Django 4.1.1 on 2022-12-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0028_train_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='chair_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_class', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='station_name',
            name='chair_class',
        ),
    ]
