# Generated by Django 4.1.1 on 2022-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0031_train_info_delete_chair_class_delete_train_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_info',
            name='from_dist',
        ),
        migrations.RemoveField(
            model_name='train_info',
            name='to_dist',
        ),
        migrations.AlterField(
            model_name='train_info',
            name='place',
            field=models.CharField(default='from', max_length=15),
        ),
    ]
