# Generated by Django 4.1.1 on 2022-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0033_train_info_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
