# Generated by Django 4.1.2 on 2022-12-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0035_ticket_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='child',
        ),
    ]
