# Generated by Django 4.1.2 on 2022-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0036_remove_journey_adult_remove_journey_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_info',
            old_name='passenger_mail',
            new_name='train_name',
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='arrv_tym',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='chair_class',
            field=models.CharField(default='class', max_length=15),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='dep_tym',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='dest_from',
            field=models.CharField(default='from', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='dest_to',
            field=models.CharField(default='to', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='total_seat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='train_id',
            field=models.IntegerField(default=0),
        ),
    ]
