# Generated by Django 4.1.2 on 2022-12-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0037_rename_passenger_mail_ticket_info_train_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='passenger_un',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
