# Generated by Django 4.1.2 on 2022-12-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_tick', '0038_ticket_info_passenger_un'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_info',
            name='to',
            field=models.CharField(default='to', max_length=15),
        ),
    ]
