# Generated by Django 4.1.2 on 2022-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('Nid_No', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('mobile_No', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('confirm_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
