# Generated by Django 4.1.2 on 2022-12-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_acc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
