# Generated by Django 4.1.2 on 2022-12-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_acc', '0004_remove_passenger_address_passenger_house_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='tourist',
        ),
    ]
