# Generated by Django 4.1.1 on 2022-12-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_login_details'),
        ('forgetPass', '0002_delete_forget_password1'),
        ('create_acc', '0005_remove_passenger_tourist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger',
        ),
    ]
