# Generated by Django 4.1.2 on 2022-12-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_acc', '0002_remove_passenger_id_alter_passenger_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample3', to='create_acc.passenger')),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample4', to='create_acc.passenger')),
            ],
        ),
    ]
