# Generated by Django 4.1.1 on 2022-12-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_details',
        ),
    ]
