# Generated by Django 4.1.2 on 2022-12-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_profile', '0002_profile_update_ph_nmbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_update',
            name='f_add',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
