# Generated by Django 4.1.2 on 2022-12-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_profile', '0004_alter_profile_update_ph_nmbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_update',
            name='ph_nmbr',
            field=models.CharField(default=0, max_length=13),
        ),
    ]
